const departamentos = [
    { id: 0, nombre: 'Dpto. Arquitectura y Urbanismo', codigo: 'ARQ' },
    { id: 1, nombre: 'Dpto. Ciencias Básicas Médicas', codigo: 'CBM' },
    { id: 2, nombre: 'Dpto. Comunicación Social', codigo: 'CMN' },
    { id: 3, nombre: 'Dpto. Cs Politica y Rel Internacionales', codigo: 'POL' },
    { id: 4, nombre: 'Dpto. Derecho', codigo: 'LEY' },
    { id: 5, nombre: 'Dpto. Diseño', codigo: 'DIG' },
    { id: 6, nombre: 'Dpto. Educación', codigo: 'EDU' },
    { id: 7, nombre: 'Dpto. Enfermería', codigo: 'ENF' },
    { id: 8, nombre: 'Dpto. Español', codigo: 'LIN' },
    { id: 9, nombre: 'Dpto. Física', codigo: 'FIS' },
    { id: 10, nombre: 'Dpto. Historia y Cs. Sociales', codigo: 'HIS' },
    { id: 11, nombre: 'Dpto. Humanidades y Filosofía', codigo: 'FIL' },
    { id: 12, nombre: 'Dpto. Ing. Civil y Ambiental', codigo: 'ICI' },
    { id: 13, nombre: 'Dpto. Ingeniería Básica', codigo: 'XXX' },
    { id: 14, nombre: 'Dpto. Ingeniería Industrial', codigo: 'DIN' },
    { id: 15, nombre: 'Dpto. Ingeniería Mecánica', codigo: 'IME' },
    { id: 16, nombre: 'Dpto. Ingeniería de Sistemas', codigo: 'IST' },
    { id: 17, nombre: 'Dpto. Lenguas', codigo: 'CAS' },
    { id: 18, nombre: 'Dpto. Lenguas Extranjeras', codigo: 'IGL' },
    { id: 19, nombre: 'Dpto. Matemáticas y Estadística', codigo: 'MAT' },
    { id: 20, nombre: 'Dpto. Medicina', codigo: 'CLI' },
    { id: 21, nombre: 'Dpto. Mercadeo y Neg. Internacionales', codigo: 'MDO' },
    { id: 22, nombre: 'Dpto. Minors Ingenierias', codigo: 'XXX' },
    { id: 23, nombre: 'Dpto. Música', codigo: 'MUS' },
    { id: 24, nombre: 'Dpto. Odontología', codigo: 'ODO' },
    { id: 25, nombre: 'Dpto. Psicología', codigo: 'PSI' },
    { id: 26, nombre: 'Dpto. Química y Biología', codigo: 'BIO' },
    { id: 27, nombre: 'Dpto. Relaciones Internacionales', codigo: 'PML' },
    { id: 28, nombre: 'Dpto. Salud Pública', codigo: 'SBP' },
    { id: 29, nombre: 'Dpto. Tecnología', codigo: 'XXX' },
    { id: 30, nombre: 'Dpto. de Economía', codigo: 'ECO' },
    { id: 31, nombre: 'Dpto. Finanzas y Organizaciones', codigo: 'FIN' },
    { id: 32, nombre: 'Dpto. Eléctrica-Electrónica', codigo: 'TEL' },
];

module.exports = departamentos;